// -----------------------------------------------------------------------------------------------------
// | <auto-generated>                                                                                  |
// |    This code was generated by a tool.                                                             |
// |                                                                                                   |
// |    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. |
// | </auto-generated>                                                                                 |
// -----------------------------------------------------------------------------------------------------

// Define JSON file path variable for easy adjustment
using System;
using System.Collections.Generic;

namespace Tunetastic;
public partial class NavigationPageMappings
{
    public static Dictionary<string, Type> PageDictionary { get; } = new Dictionary<string, Type>
    {
        {"Tunetastic.Views.MainPlayerPage", typeof(Tunetastic.Views.MainPlayerPage)},
        {"Tunetastic.Views.LibraryViews.AllSongsViewPage", typeof(Tunetastic.Views.LibraryViews.AllSongsViewPage)},
        {"Tunetastic.Views.LibraryViews.ArtistsViewPage", typeof(Tunetastic.Views.LibraryViews.ArtistsViewPage)},
        {"Tunetastic.Views.LibraryViews.AlbumsViewPage", typeof(Tunetastic.Views.LibraryViews.AlbumsViewPage)},
        {"Tunetastic.Views.LibraryViews.GenresViewPage", typeof(Tunetastic.Views.LibraryViews.GenresViewPage)},
        {"Tunetastic.Views.LibraryViews.YearsViewPage", typeof(Tunetastic.Views.LibraryViews.YearsViewPage)},
        {"Tunetastic.Views.PlaylistViews.QueuedList", typeof(Tunetastic.Views.PlaylistViews.QueuedList)},
        {"Tunetastic.Views.PlaylistViews.RecentlyAdded", typeof(Tunetastic.Views.PlaylistViews.RecentlyAdded)},
        {"Tunetastic.Views.PlaylistViews.MostPlayed", typeof(Tunetastic.Views.PlaylistViews.MostPlayed)},
    };
}
