name: Build

on:
  pull_request:
    branches: [ "master", "Development" ]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        platform: [ x64, arm64 ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      - name: Restore NuGet packages
        run: dotnet restore Tunetastic.sln --configfile nuget.config

      - name: Build (${{ matrix.platform }})
        run: msbuild Tunetastic.sln /p:Configuration=Release /p:Platform=${{ matrix.platform }}
