name: Build

on:
  pull_request:
    branches: [ "master", "Development" ]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        platform: [ x64, arm64 ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      - name: Add CommunityToolkit Labs NuGet source
        run: nuget sources add -Name "CommunityToolkit-Labs" -Source "https://pkgs.dev.azure.com/dotnet/CommunityToolkit/_packaging/CommunityToolkit-Labs/nuget/v3/index.json"

      - name: Restore NuGet packages
        run: nuget restore Tunetastic.sln

      - name: Build (${{ matrix.platform }})
        run: msbuild Tunetastic.sln /p:Configuration=Release /p:Platform=${{ matrix.platform }}
